package com.bkf.busi.flowmanage.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table flow_order
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FlowOrder extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   车牌号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.plate_number
     *
     * @mbg.generated
     */
    private String plateNumber;

    /**
     * Database Column Remarks:
     *   厂牌型号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.standard_name
     *
     * @mbg.generated
     */
    private String standardName;

    /**
     * Database Column Remarks:
     *   投保人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.applicant_name
     *
     * @mbg.generated
     */
    private String applicantName;

    /**
     * Database Column Remarks:
     *   引流时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * Database Column Remarks:
     *   引流渠道code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.channel_id
     *
     * @mbg.generated
     */
    private String channelId;

    /**
     * Database Column Remarks:
     *   投保状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.insure_status
     *
     * @mbg.generated
     */
    private String insureStatus;

    /**
     * Database Column Remarks:
     *   保单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.policy_no
     *
     * @mbg.generated
     */
    private String policyNo;

    /**
     * Database Column Remarks:
     *   结算状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.settlement_status
     *
     * @mbg.generated
     */
    private String settlementStatus;

    /**
     * Database Column Remarks:
     *   结算批次
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.settlement_no
     *
     * @mbg.generated
     */
    private String settlementNo;

    /**
     * Database Column Remarks:
     *   结算时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.settlement_time
     *
     * @mbg.generated
     */
    private Date settlementTime;

    /**
     * Database Column Remarks:
     *   扩展字段1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.remark1
     *
     * @mbg.generated
     */
    private String remark1;

    /**
     * Database Column Remarks:
     *   扩展字段2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_order.remark2
     *
     * @mbg.generated
     */
    private String remark2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.id
     *
     * @return the value of flow_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.id
     *
     * @param id the value for flow_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.phone
     *
     * @return the value of flow_order.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.phone
     *
     * @param phone the value for flow_order.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.plate_number
     *
     * @return the value of flow_order.plate_number
     *
     * @mbg.generated
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.plate_number
     *
     * @param plateNumber the value for flow_order.plate_number
     *
     * @mbg.generated
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.standard_name
     *
     * @return the value of flow_order.standard_name
     *
     * @mbg.generated
     */
    public String getStandardName() {
        return standardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.standard_name
     *
     * @param standardName the value for flow_order.standard_name
     *
     * @mbg.generated
     */
    public void setStandardName(String standardName) {
        this.standardName = standardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.applicant_name
     *
     * @return the value of flow_order.applicant_name
     *
     * @mbg.generated
     */
    public String getApplicantName() {
        return applicantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.applicant_name
     *
     * @param applicantName the value for flow_order.applicant_name
     *
     * @mbg.generated
     */
    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.create_time
     *
     * @return the value of flow_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.create_time
     *
     * @param createTime the value for flow_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.modify_time
     *
     * @return the value of flow_order.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.modify_time
     *
     * @param modifyTime the value for flow_order.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.channel_id
     *
     * @return the value of flow_order.channel_id
     *
     * @mbg.generated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.channel_id
     *
     * @param channelId the value for flow_order.channel_id
     *
     * @mbg.generated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.insure_status
     *
     * @return the value of flow_order.insure_status
     *
     * @mbg.generated
     */
    public String getInsureStatus() {
        return insureStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.insure_status
     *
     * @param insureStatus the value for flow_order.insure_status
     *
     * @mbg.generated
     */
    public void setInsureStatus(String insureStatus) {
        this.insureStatus = insureStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.policy_no
     *
     * @return the value of flow_order.policy_no
     *
     * @mbg.generated
     */
    public String getPolicyNo() {
        return policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.policy_no
     *
     * @param policyNo the value for flow_order.policy_no
     *
     * @mbg.generated
     */
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.settlement_status
     *
     * @return the value of flow_order.settlement_status
     *
     * @mbg.generated
     */
    public String getSettlementStatus() {
        return settlementStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.settlement_status
     *
     * @param settlementStatus the value for flow_order.settlement_status
     *
     * @mbg.generated
     */
    public void setSettlementStatus(String settlementStatus) {
        this.settlementStatus = settlementStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.settlement_no
     *
     * @return the value of flow_order.settlement_no
     *
     * @mbg.generated
     */
    public String getSettlementNo() {
        return settlementNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.settlement_no
     *
     * @param settlementNo the value for flow_order.settlement_no
     *
     * @mbg.generated
     */
    public void setSettlementNo(String settlementNo) {
        this.settlementNo = settlementNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.settlement_time
     *
     * @return the value of flow_order.settlement_time
     *
     * @mbg.generated
     */
    public Date getSettlementTime() {
        return settlementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.settlement_time
     *
     * @param settlementTime the value for flow_order.settlement_time
     *
     * @mbg.generated
     */
    public void setSettlementTime(Date settlementTime) {
        this.settlementTime = settlementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.remark1
     *
     * @return the value of flow_order.remark1
     *
     * @mbg.generated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.remark1
     *
     * @param remark1 the value for flow_order.remark1
     *
     * @mbg.generated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_order.remark2
     *
     * @return the value of flow_order.remark2
     *
     * @mbg.generated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_order.remark2
     *
     * @param remark2 the value for flow_order.remark2
     *
     * @mbg.generated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
}