package com.bkf.busi.flowmanage.mapper;

import com.bkf.busi.flowmanage.bean.FlowOrder;

import java.util.List;

public interface FlowOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_order
     *
     * @mbg.generated
     */
    int insert(FlowOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_order
     *
     * @mbg.generated
     */
    int insertSelective(FlowOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_order
     *
     * @mbg.generated
     */
    FlowOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowOrder record);

    /*
     *功能描述 分页查询
     * @author wangxuefei
     * @date 2020/12/8
     * @param dataMap
     * @return java.util.List<com.bkf.busi.flowmanage.bean.FlowOrder>
     */
    List<FlowOrder> findFlowOrderByPage();
}